/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tryvehicle;

import com.google.inject.assistedinject.Assisted;
import example.virtualvehicle.ExampleProcessModel;
import example.virtualvehicle.ExampleProcessModelTO;
import example.virtualvehicle.StateResponse;
import java.util.Objects;
import static java.util.Objects.requireNonNull;
import javax.inject.Inject;
import javax.swing.SwingUtilities;
import org.opentcs.components.kernel.services.PlantModelService;
import org.opentcs.components.kernel.services.VehicleService;
import org.opentcs.customizations.ServiceCallWrapper;
import org.opentcs.drivers.vehicle.VehicleProcessModel;
import org.opentcs.drivers.vehicle.management.VehicleCommAdapterPanel;
import org.opentcs.drivers.vehicle.management.VehicleProcessModelTO;
import org.opentcs.util.CallWrapper;

/**
 *
 * @author Lenovo
 */
public class Vehicle
    extends VehicleCommAdapterPanel {

  /**
   * Creates new form NewJPanel
   */
  
  
 private ExampleProcessModelTO processModel;
 private VehicleService vehicleService;
 private CallWrapper callWrapper;

 @Inject
  public Vehicle(@Assisted ExampleProcessModelTO processModel,
  @Assisted VehicleService vehicleService,
  @ServiceCallWrapper CallWrapper callWrapper) {
  this.processModel = requireNonNull(processModel, "processModel");
  this.vehicleService = requireNonNull(vehicleService, "vehicleService");
  this.callWrapper = requireNonNull(callWrapper, "callWrapper");
  initGuiContent();
  initComponents();
  
  }
   private void initGuiContent() {
    // Trigger an update for all attributes once first.
    for (VehicleProcessModel.Attribute attribute : VehicleProcessModel.Attribute.values()) {
      processModelChange(attribute.name(), processModel);
    }
    for (ExampleProcessModel.Attribute attribute : ExampleProcessModel.Attribute.values()) {
      processModelChange(attribute.name(), processModel);
    }
  }
  @Override
  public void processModelChange(String attributeChanged, VehicleProcessModelTO newprocessModel) {
     if (!(newprocessModel instanceof ExampleProcessModelTO)) {
      return;
    }
    processModel = (ExampleProcessModelTO) newprocessModel;

    if (Objects.equals(attributeChanged,
                       VehicleProcessModel.Attribute.COMM_ADAPTER_CONNECTED.name())) {
     // updateCommAdapterConnected(processModel.isCommAdapterConnected());
    }
    else if (Objects.equals(attributeChanged,
                            ExampleProcessModel.Attribute.CURRENT_STATE.name())) {
      updateCurrentState(processModel.getCurrentState());
    }else if(Objects.equals(attributeChanged,VehicleProcessModel.Attribute.POSITION.name()))
    {
    UpdateCurrentPosition(processModel.getVehiclePosition());
    }
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    label1 = new java.awt.Label();
    currentpoint = new javax.swing.JTextField();

    jButton1.setText("jButton1");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("车辆状态"));
    jPanel1.setName("vehiclestatepanel"); // NOI18N

    label1.setText("当前位置");

    currentpoint.setName("currentpostion"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(21, 21, 21)
        .addComponent(currentpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(454, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(currentpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(132, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(158, 158, 158))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(55, 55, 55))
    );

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cody/vehicle"); // NOI18N
    jPanel1.getAccessibleContext().setAccessibleName(bundle.getString("vehiclepanneltitle")); // NOI18N
    jPanel1.getAccessibleContext().setAccessibleDescription("");
    jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

    getAccessibleContext().setAccessibleName(bundle.getString("vehiclepanneltitle")); // NOI18N
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField currentpoint;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private java.awt.Label label1;
  // End of variables declaration//GEN-END:variables

  private void updateCurrentState(StateResponse currentState) {
    SwingUtilities.invokeLater(()->{updatepanel(currentState);});
  }

  private void updatepanel(StateResponse currentState) {
  currentpoint.setText( String.valueOf(currentState.getPositionId()));
  }

  private void UpdateCurrentPosition(String vehiclePosition) {
   // SwingUtilities.invokeLater(()->{update(vehiclePosition);});
  }
  private void update(String t)
  {
   currentpoint.setText( t);
  }
}
